image_width: 1620
image_height: 1220
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [813.71609,   0.     , 813.40566,
           0.     , 816.48785, 591.98312,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.264700, 0.052413, 0.000480, -0.002743, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [569.47144,   0.     , 802.88852,   0.     ,
           0.     , 664.52576, 582.93947,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
